### ISSUE TITLE
Testing 3rd party auth flows

### ISSUE THREAD

**Issue by zacharynevin** [jaredhanson/chai-passport-strategy#1]
Hey,

First off, love what you do. The passport libraries are easily some of the most influential node.js libraries in the express community.

I am trying to write automated tests for the `passport-facebook` strategy. To do that, I want to use Selenium Webdriver. I tried doing:

```
chai.passport.use(Strategies.facebookStrategy)
   .redirect(function() {
    // do selenium stuff here
    done();
  })
```

This isn't really working. Additionally, is there a way to specify what token gets passed to Facebook (e.g. if I want to test the OAuth flow for a special test user on Facebook).

**Comment by zacharynevin** [comment]
Oh shit I put in `.authorize()` and I got a url. I think I can do this.

**Comment by zacharynevin** [comment]
Yeah I can't do this. Is there a library for mocks in passport? How would you suggest I test the third party services? I don't really need to test that the Facebook auth itself works, I just want to test the function after it. I could just unit test that function.

**Comment by jaredhanson** [comment]
This package is meant for unit testing Passport strategies.  It's not intended to be used with integration tests or unit testing of verify callbacks and the like.

I don't have any specific guidance on application-level integration tests.
